import { AIModelTool } from '../types';

export const POPULAR_AI_TOOLS: AIModelTool[] = [
  {
    id: 'gemini-3.6-flash',
    name: 'Google Gemini 3.6 Flash',
    provider: 'Google AI Studio',
    icon: 'Sparkles',
    badge: 'Active Engine',
    description: 'Ultra-fast low latency stream model for conversational AI & real-time global translation.',
    status: 'active',
    color: 'from-blue-500 to-indigo-600',
    capabilities: ['Live SSE Streaming', '35+ Languages', 'Real-time JSON Translation', 'Voice Audio TTS'],
  },
  {
    id: 'gpt-4o-realtime',
    name: 'OpenAI GPT-4o Realtime',
    provider: 'OpenAI',
    icon: 'Zap',
    badge: 'API Connected',
    description: 'Multimodal voice-to-voice stream model with speech synthesis.',
    status: 'available',
    color: 'from-emerald-500 to-teal-600',
    capabilities: ['Speech-to-Speech', 'Expressive Voice', 'Low Latency'],
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Anthropic Claude 3.5 Sonnet',
    provider: 'Anthropic',
    icon: 'Cpu',
    badge: 'High Precision',
    description: 'Nuanced multilingual translation with cultural context understanding.',
    status: 'available',
    color: 'from-amber-500 to-orange-600',
    capabilities: ['Context Nuance', 'Idiom Translation', 'Formal/Informal Register'],
  },
  {
    id: 'elevenlabs-v2',
    name: 'ElevenLabs Multilingual v2',
    provider: 'ElevenLabs',
    icon: 'Volume2',
    badge: 'Ultra Natural Voice',
    description: 'Human-like emotional voice synthesis for translation playbacks.',
    status: 'available',
    color: 'from-purple-500 to-pink-600',
    capabilities: ['Voice Cloning', '29 Languages', 'Emotional Cadence'],
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek-V3 Voice Agent',
    provider: 'DeepSeek',
    icon: 'Bot',
    badge: 'Fast Inference',
    description: 'High performance open-weights reasoning & cross-lingual parsing.',
    status: 'available',
    color: 'from-cyan-500 to-blue-600',
    capabilities: ['Cross-lingual Reasoning', 'Slang Translation'],
  },
  {
    id: 'whisper-v3',
    name: 'OpenAI Whisper v3',
    provider: 'OpenAI',
    icon: 'Mic',
    badge: 'Universal STT',
    description: 'Robust automatic speech recognition across noisy backgrounds.',
    status: 'active',
    color: 'from-rose-500 to-red-600',
    capabilities: ['Noisy Audio STT', '100+ Languages', 'Accent Robustness'],
  },
];
